### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by MikeWent** [satcar77/miband4#1]
It seems like Python 2.7 is now deprecated and used only by a bunch of legacy scripts.

There is an official statement, confirmed by python.org and pip maintainers:

```Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support```

See also [pythonclock.org](https://pythonclock.org/), it has a reference to [PEP 373](https://www.python.org/dev/peps/pep-0373/).

---

Your script is awesome and deserves better future for it!

**Comment by satcar77** [comment]
Thank you. I will start working to upgrade it.

**Comment by satcar77** [comment]
I have upgraded the script to work with Python 3. Thank you very much for pointing the need.
