### ISSUE TITLE
Obtaining realtime sensor data

### ISSUE THREAD

**Issue by maxxxpavlov** [satcar77/miband4#11]
I want to receive accelerator data from mi band 4, but there is no callback in **start_heart_rate_realtime**.

**Comment by rayavarapuvikram1** [comment]
How to get accelerometer values?

**Comment by satcar77** [comment]
Assign a callback function to **accel_raw_callback** and call **start_heart_rate_realtime** . See if you can get any values. I haven't implemented the feature fully.

**Comment by rayavarapuvikram1** [comment]
Is it possible to set an alarm with python?

**Comment by satcar77** [comment]
That feature is on the project's TODO list.
