### ISSUE TITLE
Can't read recent activity data

### ISSUE THREAD

**Issue by MrVinceZ** [satcar77/miband4#16]
Hello ! 

I'm working with your plugin to detect when I'm sleeping. 

To do that, I want to get back my activity data for the last hour, but I receive nothing after 10:30 this morning (17h20 when I write this)

Do you have an idea of where I need to search ?

Thank you for your jobs, it will help me a lot 👍

**Comment by satcar77** [comment]
This is not the first time I am hearing this issue. I now realize that I hardcoded that last \x17 byte, which could be a field representing timezone. It was \x17 for my watch.
https://github.com/satcar77/miband4/blob/0935d0d85e8fefbd909e7c97a2e3023342e3f08d/miband.py#L526

I have to work on it, do some research. I will get back to you soon.

**Comment by MrVinceZ** [comment]
Oh, if this can help, I'm on Paris' Timezone : UTC+2 

Thank you for your answer !

**Comment by satcar77** [comment]
I have updated the code. Now, the user's timezone is fetched from the band and is used to make the request for activity data. I hope this solves the issue.

**Comment by MrVinceZ** [comment]
Seems solved ! Thank you :)
