### ISSUE TITLE
More info on ACL packet debugging

### ISSUE THREAD

**Issue by opensourcerebel** [satcar77/miband4#17]
Can you share more info on this " I reverse engineered snooped ACL packets to fill in the pieces of the puzzle." what steps did you took to get the packets - something that a contributor can replicate?

**Comment by satcar77** [comment]
Yes, I used the android's bluetooth HCI snoop log and wireshark to open that log file to analyze it. Use the feature that you want to investigate in the MiFit app. The communication between the band will be recorded in the HCI log file. Copy that log file to your computer and investigate the ACL packets going in and out, deducing what kind of data does each of the fields represents in the individual packet.
