### ISSUE TITLE
Stop call notification

### ISSUE THREAD

**Issue by mfernandanll** [satcar77/miband4#18]
Hi,

I'm working on project with miband 4 and I have a doubt about the band.disconnect() method, I'm trying to create a loop that connect the band, then make a call (notification type 3), disconnect the band and finally connect again and make que whole process again. 
The problem is that disconnect method from bluepy.btle is disconnecting the band, but the call doesn't end at all. So, do you have any way of stop a call?

**Comment by satcar77** [comment]
The waitfornotification method of bluepy can be used to control the duration of the call message to be displayed in the band. For me, calling the disconnect method instantaneously stops the call. I can't seem to get your problem. Would you mind providing me with more info?
