### ISSUE TITLE
Question-Request

### ISSUE THREAD

**Issue by Scorpion2185** [satcar77/miband4#20]
I have a rooted phone.
`sqlite3 /data/data/com.xiaomi.hm.health/databases/origin_db_[YOURDBNAMEHERE] "select AUTHKEY from DEVICE"`
Is "[YOURDBNAMEHERE]" a value to change? My DB? What is DB?
What is supposed to do that command? Does it create a file? 

In data/data/com.xiaomi.hm.health/ there isn' t the folder database. Is this normal? 

Can you make something to avoid to use android (initial pairing)?

**Comment by satcar77** [comment]
Your phone has to be rooted to access the data/data/ folder and you should have a superuser privilege to execute the commands.  do `ls /data/data/com.xiaomi.hm.health/databases/` to list all the files in the directory. The files have the format of origin_db_[some number]. Then do  `sqlite3 /data/data/com.xiaomi.hm.health/databases/<name of your database file you got earlier> "select AUTHKEY from DEVICE"`. What this command does is it executes the select sqlite command to read AUTHKEY column in the DEVICE table inside of the database file you provide.

**Comment by Scorpion2185** [comment]
What terminal app do you use? I can' t use `su` or `sudo` on termux.
```
$ whoami
u0_a93
```
I rooted the phone and installed a custom ROM, I am not sure now if the phone is rooted.

**Comment by satcar77** [comment]
In my case, I connected my phone to the PC in debugging mode and used adb shell.

**Comment by Scorpion2185** [comment]
So:
`adb shell`
Were you already root? Or did you use `su`?

I can' t use `su`:
```
$ su
/system/bin/sh: su: not found

```
Did you root the phone with Magisk or SuperSU using TWRP maybe?

**Comment by satcar77** [comment]
The root method is irrelevant, all you need is root access to the system directories. You could try accessing the file using a good file explorer with root access, copy it to a different directory, and open it with any SQLite editor. Mine was rooted with Magisk and was flashed with TWRP.

**Comment by Scorpion2185** [comment]
I would have liked to root the phone but since I don' t use it much I decided to use the modded Mi Fit app.
Indeed I would like to use only the computer instead of the phone.
But this project doesn't have the settings, sleep monitoring and more.
Can you add all the features of the Mi Fit app and the watch faces support?

**Comment by Scorpion2185** [comment]
I would have liked to root the phone but since I don' t use it much I decided to use the modded Mi Fit app.
Indeed I would like to use only the computer instead of the phone.
But this project doesn't have the settings, sleep monitoring and more.
Can you add all the features of the Mi Fit app and watch faces support?
