### ISSUE TITLE
send messege NOT WORK !

### ISSUE THREAD

**Issue by mr-tafreshi** [satcar77/miband4#24]
Hi. on ubuntu 20.10 and miband4 firmware version  v.10.9.66 send messege call/mail/sms not work !

**Comment by besimali** [comment]
had the same problem. Got it working by providing the auth key

**Comment by besimali** [comment]
It seems like the firmware version is the issue. 
I installed the Mi fit app from freemyband.com in order to get the auth key, but it also seems to have downgraded the firmware to 1.0.9.48. With this firmware the notifications go through without the auth key as well.

**Comment by janvda** [comment]
I think you can close this ticket.
