### ISSUE TITLE
Oops...some functions have some bugs on my device.

### ISSUE THREAD

**Issue by FinchZ** [satcar77/miband4#3]
MiBand
Soft revision: V1.0.7.14
Hardware revision: V0.25.131.21
Serial: bbba6d66d3d7
Battery: 25
Time: 2019-11-30T23:46:54

I can't retrive music state.
I can't send call message.The device has no output.
Is a problem of the version?

**Comment by MrSwiss** [comment]
@FinchZ  I have same problems, how do you solve it.
Thanks

**Comment by satcar77** [comment]
I have made some changes to the code. I hope this fixes your problems. Please let me know.

**Comment by MrSwiss** [comment]
@satcar77 Thanks for bug fixing, currently I'm not at home, so I can't test it. I will report back when I got home in next few day.

**Comment by MrSwiss** [comment]
@satcar77 I had use you lastest commit it still dosn't work.
For Debug infomation.
I doesn't had authkey

When I select 1- Get general info of the device
"MiBand
Soft revision: V1.0.7.44
Hardware revision: V0.25.17.5
Serial: 08871d1255e5
Battery: 64
Time: 2019-12-21T18:59:28
Press a key to continue"

I can fake music name. console response to button press.
But when I select to send message notting happend.

**Comment by FinchZ** [comment]
Thank you very much!
I test all functions.
And they work successfully now!
It's very cool!!!

**Comment by FinchZ** [comment]
Hello,I find it's a little difficult to intall bluetooth library for python.
But I have a try to translate it into a C# version.
Now it can work on Windows.
And I try to reverse the XiaoMi Unlock APP(an app can unlock windows10 by miband.)
I find that I can add more good functions to it.
![screenshot](https://user-images.githubusercontent.com/46061991/71570580-f51cd500-2b10-11ea-9a1f-f47816cf2662.png)

**Comment by satcar77** [comment]
Yes @FinchZ , the bluetooth library, BluePy, which this project is using, only works for Linux. So did you you translate the code in python to C# so that it could be used for windows? If so, well done.  you are always welcome to contribute to this project. Thank you
