### ISSUE TITLE
SetAlarm

### ISSUE THREAD

**Issue by Tuxicoman2** [satcar77/miband4#7]
Hi,

I worked on debugging the setAlarm function in Gadgetbridge (see https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/1747 )
So I though it would be easy to port the function to Python now that I better understand the data.
I wrote this  but it doesn't work :

```
    def set_alarm(self, hour=11, minute=15):
        print("set_alarm")
        char = self.svc_1.getCharacteristics(UUIDS.CHARACTERISTIC_CONFIGURATION)[0]
        alarm_id = 0
        alarm_tag = 128+alarm_id #Create or update alarm
        repetition_mask = 31 #All days
        packet = struct.pack("5H",2,alarm_tag,hour,minute,repetition_mask)
        print("packet", packet)
        val = char.write(packet, True)
        print("done")
        return val
```

Any help or hint is welcome

**Comment by satcar77** [comment]
The type of data that you are packing with struct is unsigned short while I saw that the code from gadgetbridge declares byte for the individual parameters to send. To interpret the data as unsigned byte you should use 'B' instead of 'H'. Maybe that fixes it? Here is the documentation of struct https://docs.python.org/2/library/struct.html

**Comment by nico202** [comment]
Hi @Tuxicoman2 , I was able to set an alarm with your code, just by changing this:

```python
val = char.write(packet, False)
```

**Comment by nico202** [comment]
I realized only now how old this issue is.  I opened a [PR](https://github.com/satcar77/miband4/pull/40), please check if it works if you are still using this

**Comment by satcar77** [comment]
@nico202 I have accepted your pull request. Cheers. Thank you for the contribution.
